### ISSUE TITLE
Practica DLL

### ISSUE THREAD

**Issue by garaudy12** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-garaudy12#2]
[Practica DLL - Solano Mendoza Taoli.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-garaudy12/files/6333110/Practica.DLL.-.Solano.Mendoza.Taoli.pdf)

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 17.8/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
